// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5XotRJl5QRxPXSsl33VrJ2VbLu_AH68',
    appId: '1:162138719619:android:2fd61c675428f650c5e2b6',
    messagingSenderId: '162138719619',
    projectId: 'loadum-66455',
    storageBucket: 'loadum-66455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCesOenL7G5Wv1T5d5LljL3B5c_MjFzIQk',
    appId: '1:162138719619:ios:542fd32eb5a436c1c5e2b6',
    messagingSenderId: '162138719619',
    projectId: 'loadum-66455',
    storageBucket: 'loadum-66455.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuFK4XBRMM0dZ-jiIejNI6l-P1NiNxiB4',
    appId: '1:162138719619:web:7960e5d0df398b63c5e2b6',
    messagingSenderId: '162138719619',
    projectId: 'loadum-66455',
    authDomain: 'loadum-66455.firebaseapp.com',
    storageBucket: 'loadum-66455.firebasestorage.app',
    measurementId: 'G-3JQ6SXSEZN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCesOenL7G5Wv1T5d5LljL3B5c_MjFzIQk',
    appId: '1:162138719619:ios:3e7a01b250b63b65c5e2b6',
    messagingSenderId: '162138719619',
    projectId: 'loadum-66455',
    storageBucket: 'loadum-66455.firebasestorage.app',
    iosBundleId: 'com.example.flutexAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuFK4XBRMM0dZ-jiIejNI6l-P1NiNxiB4',
    appId: '1:162138719619:web:d621c7eea7ef1fdfc5e2b6',
    messagingSenderId: '162138719619',
    projectId: 'loadum-66455',
    authDomain: 'loadum-66455.firebaseapp.com',
    storageBucket: 'loadum-66455.firebasestorage.app',
    measurementId: 'G-0Y7977RZBZ',
  );

}